from dotenv import load_dotenv
import os

load_dotenv()

REDIS_URL = os.getenv("REDIS_URL")
SQLALCHEMY_DATABASE_URL = os.getenv("SQLALCHEMY_DATABASE_URL")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
STABILITYAI_APIKEY = os.getenv("STABILITYAI_APIKEY")
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")
REGION = os.getenv("REGION")
BUCKET_NAME = os.getenv("BUCKET_NAME")
EMAIL = os.getenv("EMAIL")
DOMAIN = os.getenv("DOMAIN")
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_BASE_URL = "https://api.paystack.co"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_MINUTES = 60
SCRAPING_ANT_API_KEY = os.getenv("SCRAPING_ANT_API_KEY")
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GOOGLE_GEMINI_KEY = os.getenv("GOOGLE_GEMINI_KEY")
EXPIRATION = 300
MONGO_DB_URL = os.getenv("MONGO_DB_URL")
UNSTRUCTURED_API_KEY = os.getenv("UNSTRUCTURED_API_KEY")
BREVO_KEY = os.getenv("BREVO_API_KEY")
IPINFO_ACCESS_KEY = os.getenv("IPINFO_KEY")
os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_GEMINI_KEY")
PAYSTACK_IPS = ["52.31.139.75", "52.49.173.169", "52.214.14.220"]
